spring:
  application:
    name: bulkdb-insert
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: password
    hikari:
      register-mbeans: true
      minimumIdle: 2
      maximumPoolSize: 50
      max-lifetime: 600000


#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: TRACE
#        HikariConfig: DEBUG

##chose from bulk,single, singleparallel
bulkupload:
  insert:
    mode: singleparallel